
// Objective-C API for talking to the following Go packages
//
//	client
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bond_FRAMEWORK_H__
#define __Bond_FRAMEWORK_H__

#include "Client.objc.h"
#include "Universe.objc.h"

#endif
